# Generated by Django 5.0.4 on 2024-06-27 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('current_occupation', models.CharField(max_length=100)),
                ('employer_name', models.CharField(blank=True, max_length=100)),
                ('work_address', models.TextField(blank=True)),
                ('work_contact_number', models.CharField(blank=True, max_length=20)),
                ('educational_background', models.TextField()),
                ('areas_of_interest', models.CharField(choices=[('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Environment', 'Environment'), ('Human Rights', 'Human Rights'), ('Poverty Alleviation', 'Poverty Alleviation'), ('Community Development', 'Community Development'), ('Technology and innovation', 'Technology and innovation'), ('Leadership development', 'Leadership development'), ('Youth Empowerment', 'Youth Empowerment'), ('Others', 'Others')], max_length=100)),
                ('volunteer_experience', models.TextField(blank=True)),
                ('reasons_for_joining', models.TextField()),
                ('availability_hours_per_week', models.IntegerField()),
                ('availability_days', models.CharField(max_length=100)),
                ('skills_qualifications', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_relationship', models.CharField(max_length=100)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('medical_conditions', models.TextField(blank=True)),
                ('authorized_to_work', models.BooleanField()),
                ('criminal_convictions', models.BooleanField()),
                ('how_heard', models.CharField(blank=True, max_length=255)),
                ('promise', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
