# Generated by Django 5.0.4 on 2024-06-16 15:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('token', models.CharField(max_length=150)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('profile', models.ImageField(default='profile/avatar.jpg', upload_to='profile')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(default='/position/default.jpg', upload_to='position')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'positions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=255)),
                ('work_address', models.CharField(max_length=255)),
                ('interests', models.CharField(choices=[('Education', 'Education'), ('Human Rights', 'Human Rights'), ('Poverty Alleviation', 'Poverty Alleviation'), ('Community Development', 'Community Development'), ('Technology and Innovation', 'Technology and Innovation'), ('Leadership Development', 'Leadership Development'), ('Healthcare', 'Healthcare'), ('Youth Empowerment', 'Youth Empowerment'), ('Other', 'Other')], max_length=100)),
                ('other_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('work_contact', models.CharField(max_length=20)),
                ('education_background', models.TextField()),
                ('volunteered_before', models.BooleanField()),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('interest_reason', models.TextField()),
                ('availability_hours', models.TextField()),
                ('availability_days', models.TextField()),
                ('skills_qualifications', models.TextField()),
                ('languages', models.TextField()),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('authorized_to_work', models.BooleanField(default=False)),
                ('criminal_convictions', models.BooleanField(default=False)),
                ('how_did_you_hear', models.TextField()),
                ('promise', models.TextField()),
                ('agree_to_pay_fee', models.BooleanField(default=False)),
                ('declaration', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
