# Generated by Django 5.0.4 on 2024-06-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerApplication',
        ),
    ]
